In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df_mas = pd.read_excel("Master_data_excel (1).xlsx")
df_mas

      ID               NAME LOCATION        DEPT  AGE
0   A001  HARTEJ SINGH ASSI   Mumbai       sales   23
1   A002  BHAVESH BALDANIYA    Delhi  technology   35
2   A003       YASH BAVISHI    Delhi  production   22
3   A004     SHREEKARA BHAT   Indore       sales   34
4   A005        KUNAL BHATT   Mumbai  technology   31
..   ...                ...      ...         ...  ...
85  L039      SOHAM VASUDEO   Mumbai  technology   36
86  L040      RITIKA SHETTY   Mumbai   marketing   37
87  L041     RUSHABH JADHAV     Pune  production   49
88  L042     SAMIKSHA SARDA     Pune       sales   33
89  L043     YASH CHAUDHARI   Indore       sales   24

[90 rows x 5 columns]

In [3]:
df_mas.isnull().sum()

ID          0
NAME        0
LOCATION    0
DEPT        0
AGE         0
dtype: int64

In [4]:
df_crick = pd.read_excel("Cricket.xlsx")
df_crick

      ID                NAME  LOCATION        DEPT  AGE
0   A001   HARTEJ SINGH ASSI    Mumbai       sales   23
1   A002   BHAVESH BALDANIYA     Delhi  technology   35
2   A005         KUNAL BHATT    Mumbai  technology   31
3   A007    SURESH CHAUDHARY     Delhi       sales   28
4   A009    CHIRAG CHOUDHARY      Pune       sales   40
5   A011  MIHIR DHANGDHARIYA    Mumbai  technology   33
6   A012        SANKET GADGE      Pune   marketing   33
7   A013         ANIKET GAMI    Indore  production   42
8   A015       ANAMICA GUPTA    Mumbai       sales   27
9   A016      YOSUFF HUSSAIN      Pune       sales   29
10  A017    AGHA AYAAN HYDER      Pune  production   22
11  A018         ISHWAR IYER     Delhi  production   29
12  A020          RIYA KADAM    Mumbai   marketing   34
13  A021         KARAN KAMAT      Pune  technology   44
14  A026       NIDHI MADNANI  Hydrabad  technology   38
15  A030       AZRIEL MENDES      Pune  production   48
16  A031        ADITYA MENON  Hydrabad  production   43
17  A032       ISHANT MISHRA    Indore   marketing   24
18  A033          PARAG MORE    Mumbai  production   24
19  A034         ARCHIT MUNI  Hydrabad  technology   26
20  A035   MOHAMMAD NEDARIYA    Mumbai   marketing   29
21  A037      AMEY NIMBALKAR      Pune   marketing   35
22  A039     HEMISH PADHIYAR     Delhi       sales   38
23  A040       KRISHNA PALAN  Hydrabad       sales   38
24  A042         PARTH SURVE     Delhi  technology   40
25  A045        MUDIT POTDAR    Nagpur  technology   37
26  A046      PRASAD SANGALE    Indore       sales   32
27  A047       PAYAL SANKHLA     Delhi   marketing   31
28  A048        MIHIR SAWANT    Nagpur   marketing   30
29  A049         JAINIL SHAH     Delhi  technology   30
30  A050           NEHA SHAH    Nagpur  production   29
31  A052        AFRAZ SHAIKH    Indore       sales   27
32  A053      HUSSAIN SHAIKH    Nagpur       sales   23
33  A057     MADHURAM SHUKLA    Nagpur   marketing   37
34  A061       KRITI THAKRAR    Mumbai  production   24
35  A062      HARSHIT THAPAR    Nagpur   marketing   35
36  A063        ABHAY TIWARI    Mumbai       sales   33
37  A064        TULSI VAIDYA      Pune   marketing   33
38  A066        SHAYAN ZAIDI    Mumbai  technology   37
39  L002          OM AGRAWAL    Nagpur  production   30
40  L007       DHRUV CHAUHAN    Mumbai       sales   27
41  L008        ISHA GHATULE      Pune       sales   23
42  L011         ADITYA JAIN      Pune  production   29
43  L013   VEDIKA KHANDELWAL    Mumbai  technology   36
44  L014          ADITYA LAD    Nagpur   marketing   36
45  L019           RHEA NAIR      Pune  technology   33
46  L020       KAVIT NAVADIA    Mumbai   marketing   24
47  L022         SHUBH PATEL      Pune       sales   33
48  L024        GRASHI PATEL    Mumbai  technology   38
49  L027       SHARDUL PATKI    Mumbai   marketing   37
50  L029         MAYUR PAWAR    Indore       sales   49
51  L034      SHARMAD SAMANT    Indore  production   33
52  L035         SANA SAWANT    Indore   marketing   33
53  L037       RUSHIL SHARMA    Nagpur       sales   29
54  L038       SHIKHA SHARMA    Nagpur  technology   36
55  L040       RITIKA SHETTY    Mumbai   marketing   37
56  L041      RUSHABH JADHAV      Pune  production   49
57  L042      SAMIKSHA SARDA      Pune       sales   33
58  L043      YASH CHAUDHARI    Indore       sales   24

In [5]:
df_volley = pd.read_csv("Volleyball.csv")
df_volley

      ID                        NAME  LOCATION        DEPT  AGE
0   A001           HARTEJ SINGH ASSI    Mumbai       sales   23
1   A005                 KUNAL BHATT    Mumbai  technology   31
2   A007            SURESH CHAUDHARY     Delhi       sales   28
3   A009            CHIRAG CHOUDHARY      Pune       sales   40
4   A011          MIHIR DHANGDHARIYA    Mumbai  technology   33
5   A013                 ANIKET GAMI    Indore  production   42
6   A015               ANAMICA GUPTA    Mumbai       sales   27
7   A017            AGHA AYAAN HYDER      Pune  production   22
8   A018                 ISHWAR IYER     Delhi  production   29
9   A019               ATHARVA KADAM    Indore   marketing   28
10  A020                  RIYA KADAM    Mumbai   marketing   34
11  A022             RAHAT JAHA KHAN    Mumbai       sales   47
12  A024  HARIKRISHNAN KONGIPARAMBIL    Nagpur       sales   41
13  A026               NIDHI MADNANI  Hydrabad  technology   38
14  A027               NETRA MAHADIK    Mumbai  technology   38
15  A028               KUNAL MAHAJAN    Indore       sales   38
16  A031                ADITYA MENON  Hydrabad  production   43
17  A040               KRISHNA PALAN  Hydrabad       sales   38
18  A042                 PARTH SURVE     Delhi  technology   40
19  A043          YASHUVARDHAN PATEL      Pune       sales   40
20  A044            PRASHANT POOJARY    Mumbai  production   35
21  A045                MUDIT POTDAR    Nagpur  technology   37
22  A048                MIHIR SAWANT    Nagpur   marketing   30
23  A053              HUSSAIN SHAIKH    Nagpur       sales   23
24  A054             ABHISHEK SHARMA     Delhi   marketing   29
25  A055               CHAYAN SHARMA      Pune  technology   36
26  A057             MADHURAM SHUKLA    Nagpur   marketing   37
27  A059                TUSHAR SINHA    Indore  technology   33
28  A062              HARSHIT THAPAR    Nagpur   marketing   35
29  A063                ABHAY TIWARI    Mumbai       sales   33
30  A064                TULSI VAIDYA      Pune   marketing   33
31  A066                SHAYAN ZAIDI    Mumbai  technology   37
32  A067               NIDHI AGRAWAL    Mumbai   marketing   49
33  L002                  OM AGRAWAL    Nagpur  production   30
34  L011                 ADITYA JAIN      Pune  production   29
35  L013           VEDIKA KHANDELWAL    Mumbai  technology   36
36  L017               SANJANA MEHTA    Indore  technology   49
37  L019                   RHEA NAIR      Pune  technology   33
38  L022                 SHUBH PATEL      Pune       sales   33
39  L023             CHAITANYA PATEL    Mumbai  production   33
40  L027               SHARDUL PATKI    Mumbai   marketing   37
41  L034              SHARMAD SAMANT    Indore  production   33
42  L037               RUSHIL SHARMA    Nagpur       sales   29
43  L038               SHIKHA SHARMA    Nagpur  technology   36
44  L040               RITIKA SHETTY    Mumbai   marketing   37
45  L042              SAMIKSHA SARDA      Pune       sales   33
46  L043              YASH CHAUDHARI    Indore       sales   24

In [6]:
df_hock=pd.read_excel("Hockey.xlsx")
df_hock

      ID                NAME  LOCATION        DEPT  AGE
0   A002   BHAVESH BALDANIYA     Delhi  technology   35
1   A003        YASH BAVISHI     Delhi  production   22
2   A004      SHREEKARA BHAT    Indore       sales   34
3   A005         KUNAL BHATT    Mumbai  technology   31
4   A013         ANIKET GAMI    Indore  production   42
5   A014  RAHUL GIMHAVANEKAR     Delhi  production   27
6   A016      YOSUFF HUSSAIN      Pune       sales   29
7   A018         ISHWAR IYER     Delhi  production   29
8   A019       ATHARVA KADAM    Indore   marketing   28
9   A021         KARAN KAMAT      Pune  technology   44
10  A022     RAHAT JAHA KHAN    Mumbai       sales   47
11  A025       HARSH KOTHARE    Mumbai  production   36
12  A026       NIDHI MADNANI  Hydrabad  technology   38
13  A027       NETRA MAHADIK    Mumbai  technology   38
14  A030       AZRIEL MENDES      Pune  production   48
15  A035   MOHAMMAD NEDARIYA    Mumbai   marketing   29
16  A036        SUYASH NIGAM    Indore   marketing   29
17  A038         DHRUMIL OZA     Delhi  technology   36
18  A039     HEMISH PADHIYAR     Delhi       sales   38
19  A042         PARTH SURVE     Delhi  technology   40
20  A043  YASHUVARDHAN PATEL      Pune       sales   40
21  A044    PRASHANT POOJARY    Mumbai  production   35
22  A045        MUDIT POTDAR    Nagpur  technology   37
23  A046      PRASAD SANGALE    Indore       sales   32
24  A048        MIHIR SAWANT    Nagpur   marketing   30
25  A052        AFRAZ SHAIKH    Indore       sales   27
26  A053      HUSSAIN SHAIKH    Nagpur       sales   23
27  A055       CHAYAN SHARMA      Pune  technology   36
28  A056       DIVYANG SHETH    Mumbai   marketing   36
29  A057     MADHURAM SHUKLA    Nagpur   marketing   37
30  A059        TUSHAR SINHA    Indore  technology   33
31  A061       KRITI THAKRAR    Mumbai  production   24
32  A062      HARSHIT THAPAR    Nagpur   marketing   35
33  A063        ABHAY TIWARI    Mumbai       sales   33
34  L005         RAHUL BHATT    Mumbai   marketing   29
35  L007       DHRUV CHAUHAN    Mumbai       sales   27
36  L008        ISHA GHATULE      Pune       sales   23
37  L011         ADITYA JAIN      Pune  production   29
38  L014          ADITYA LAD    Nagpur   marketing   36
39  L016     ANAY MAHESHWARI    Indore       sales   37
40  L017       SANJANA MEHTA    Indore  technology   49
41  L020       KAVIT NAVADIA    Mumbai   marketing   24
42  L021           ABHAY PAI    Indore   marketing   35
43  L023     CHAITANYA PATEL    Mumbai  production   33
44  L024        GRASHI PATEL    Mumbai  technology   38
45  L029         MAYUR PAWAR    Indore       sales   49
46  L039       SOHAM VASUDEO    Mumbai  technology   36
47  L040       RITIKA SHETTY    Mumbai   marketing   37
48  L041      RUSHABH JADHAV      Pune  production   49
49  L043      YASH CHAUDHARI    Indore       sales   24

In [10]:
#2

participants=set(df_crick['ID']) & set( df_volley['ID']) & set (df_hock['ID'])

all_parts = df_mas[df_mas['ID'].isin(participants)]
all_parts

      ID             NAME  LOCATION        DEPT  AGE
4   A005      KUNAL BHATT    Mumbai  technology   31
11  A013      ANIKET GAMI    Indore  production   42
16  A018      ISHWAR IYER     Delhi  production   29
23  A026    NIDHI MADNANI  Hydrabad  technology   38
37  A042      PARTH SURVE     Delhi  technology   40
40  A045     MUDIT POTDAR    Nagpur  technology   37
43  A048     MIHIR SAWANT    Nagpur   marketing   30
47  A053   HUSSAIN SHAIKH    Nagpur       sales   23
51  A057  MADHURAM SHUKLA    Nagpur   marketing   37
55  A062   HARSHIT THAPAR    Nagpur   marketing   35
56  A063     ABHAY TIWARI    Mumbai       sales   33
66  L011      ADITYA JAIN      Pune  production   29
86  L040    RITIKA SHETTY    Mumbai   marketing   37
89  L043   YASH CHAUDHARI    Indore       sales   24

In [11]:
crick_only = set(df_crick['ID'])
volley_only = set(df_volley['ID'])
hockey_only = set(df_hock['ID'])

onl_cricket = crick_only-(volley_only|hockey_only)
onl_volley = volley_only-(crick_only|hockey_only)
onl_hockey = hockey_only-(crick_only|hockey_only)

only_one = onl_cricket | onl_volley | onl_hockey
only_one

{'A012',
 'A024',
 'A028',
 'A032',
 'A033',
 'A034',
 'A037',
 'A047',
 'A049',
 'A050',
 'A054',
 'A067',
 'L035'}

In [12]:
data = {'City': ['Pune', 'Mumbai', 'Pune', 'Delhi'],
        'Product': ['A', 'B', 'A', 'B'],
        'Sales': [100, 200, 150, 300]}

df = pd.DataFrame(data)

# Create pivot: average sales per product in each city
print(pd.pivot_table(df, values='Sales', index='City', columns='Product', aggfunc='mean'))

Product      A      B
City
Delhi      NaN  300.0
Mumbai     NaN  200.0
Pune     125.0    NaN

In [13]:
df.fillna(method="ffill", inplace=True)

/tmp/ipykernel_49791/173857299.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="ffill", inplace=True)

In [14]:
print(pd.pivot_table(df, values='Sales', index='City', columns='Product', aggfunc='mean'))

Product      A      B
City
Delhi      NaN  300.0
Mumbai     NaN  200.0
Pune     125.0    NaN

In [18]:
import sqlite3

conn = sqlite3.connect("a.db")
cursor = conn.cursor()

cursor.execute('''
    CREATE TABLE IF NOT EXISTS abs(
    ID INTEGER, Name TEXT, email TEXT 
    )
''')

num = int(input("enteries"))
for _ in range(num):
    id2 = int(input())
    name = input("")
    email = input("")

    cursor.execute("INSERT INTO abs VALUES(?, ?, ?)", (id2, name, email))
cursor.execute("SELECT * FROM abs")
print(cursor.fetchall())
conn.commit()
conn.close()

enteries 1
 1
 as
 asas

OperationalError: database is locked

In [22]:
l1 = list(map(int, input("Enter numbers separated by space: ").split()))

def mult(l1):
    result = []
    for i in l1:
        result.append(i * 4)
    return result

print(mult(l1))

Enter numbers separated by space:   1 2

[4, 8]

In [23]:
st1 = "listen"
st2 = "silent"

if sorted(st1) == sorted(st2):
    print("equal")

equal